# Generated by Django 2.0.10 on 2019-02-16 00:58

from django.db import migrations, models
import portfolio.tools


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Certificate photo', upload_to=portfolio.tools.cert_pho_path),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_desc',
            field=models.CharField(blank=True, help_text='Image description', max_length=150),
        ),
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, help_text='Experience photo', upload_to=portfolio.tools.exp_pho_path),
        ),
        migrations.AddField(
            model_name='experience',
            name='image_desc',
            field=models.CharField(blank=True, help_text='Image description', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='image1_desc',
            field=models.CharField(blank=True, help_text='Image one description', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='image2_desc',
            field=models.CharField(blank=True, help_text='Image two description', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='image3_desc',
            field=models.CharField(blank=True, help_text='Image three description', max_length=150),
        ),
    ]
