# Generated by Django 2.2.11 on 2020-12-08 16:28

from django.db import migrations, models
import portfolio.tools


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190216_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(blank=True, help_text='Certificate end date', null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover Image', upload_to=portfolio.tools.cover_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='resume',
            field=models.FileField(blank=True, help_text='Cover Image', upload_to=portfolio.tools.resume_path),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Certificate image', upload_to=portfolio.tools.cert_pho_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Due/end date. In the form;:yyyy-mm-dd (i.e, 2018-12-31)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date initiated. In the form: yyyy-mm-dd (i.e, 2018-12-31)'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(help_text='Valid email address', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Mobile number (icluding country code [234 810 0383 180])', null=True),
        ),
    ]
