# Generated by Django 2.2.11 on 2020-12-12 00:36

from django.db import migrations, models
import portfolio.tools


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201208_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='details',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='mod',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tags',
            field=models.CharField(blank=True, help_text='Hash tags. Seperated by comma', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tags',
            field=models.CharField(blank=True, help_text='Hash tags. Seperated by comma', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(help_text='Your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text='Hash tags. Seperated by comma', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('O', 'Others')], help_text='Gender', max_length=2),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload Your Resume', upload_to=portfolio.tools.resume_path),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='tags',
            field=models.CharField(blank=True, help_text='Skills. Seperated by comma', max_length=255),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
